services:
  postgres_secondary:
    container_name: postgres_secondary
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: pulse_ai
    ports:
      - "5435:5432"  # Porta diferente para evitar conflito
    volumes:
      - postgres_secondary_data:/var/lib/postgresql/data
    networks:
      - api

  # Segunda instância do Redis
  redis_secondary:
    container_name: redis_secondary
    image: redis:latest
    command: redis-server
    ports:
      - "6381:6379"  # Porta diferente para evitar conflito
    networks:
      - api

volumes:
  postgres_secondary_data:

networks:
  api:
    name: api
    external: true
